# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdFYk66aa8Ayon8NZmAb9KymOfOwHAj6
"""

import pandas as pd
import re
import matplotlib.pyplot as plt
from google.colab import files

# Step 1: Upload log
uploaded = files.upload()
log_file = list(uploaded.keys())[0]

# Step 2: Parse log with regex
pattern = re.compile(r'\[(.*?)\] "\w+ (.*?)" (\d{3}) (\d+)')
data = []

with open(log_file, 'r') as f:
    for line in f:
        match = pattern.search(line)
        if match:
            datetime_str = match.group(1)
            path = match.group(2)
            status = int(match.group(3))
            size = int(match.group(4))
            data.append([datetime_str, path, status, size])

# Step 3: Create DataFrame
df = pd.DataFrame(data, columns=['datetime','path','status','size'])
df['datetime'] = pd.to_datetime(df['datetime'])

# Step 4: Count requests per minute
requests_per_min = df.groupby(df['datetime'].dt.floor('T')).size()

# Step 5: Plot requests
plt.figure(figsize=(15,5))
plt.plot(requests_per_min.index, requests_per_min.values, color='red')
plt.xlabel('Time')
plt.ylabel('Requests per minute')
plt.title('Web Server Requests')
plt.show()

# Step 6: Detect DDoS (threshold method)
threshold = requests_per_min.mean() + 3*requests_per_min.std()
ddos_times = requests_per_min[requests_per_min > threshold]

print("Detected possible DDoS intervals:")
print(ddos_times)

# Save results for GitHub
import os
os.makedirs('task_3', exist_ok=True)
ddos_times.to_csv('task_3/ddos_intervals.csv')